In [2]:
import pandas as pd

In [17]:
df=pd.read_csv("C:/P.Deekshitha/student.csv")

In [18]:
df

     Column1  Column2
0     vineet        1
1     hisham        2
2        raj        3
3      ajeet        4
4     sujit         5
5     ramesh        6
6      priya        7
7   priyanka        8
8     suresh        9
9     ritesh       10
10    hitesh       11
11     jatin       12
12   chitesh       13
13     suman       14
14     raman       15
15      aman       16
16      ravi       17
17    shravi       18
18    chavvi       19
19  himanshu       20

In [34]:
x=pd.read_csv("C:/Users/admin/Downloads/result.txt",sep=",",names=['Roll no','result'])

In [37]:
x

     Roll no  result
0    1\tfail     NaN
1    2\tfail     NaN
2    3\tpass     NaN
3    4\tpass     NaN
4    5\tfail     NaN
5    6\tpass     NaN
6    7\tfail     NaN
7    8\tpass     NaN
8    9\tpass     NaN
9   10\tpass     NaN
10  11\tpass     NaN
11  12\tfail     NaN
12  13\tfail     NaN
13  14\tfail     NaN
14  15\tpass     NaN
15  16\tpass     NaN
16  17\tpass     NaN
17  18\tpass     NaN
18  19\tpass     NaN
19  20\tfail     NaN

In [29]:
y=pd.read_csv("result.txt",sep="/t",names=['Roll no','result'])

C:\Users\admin\AppData\Local\Temp\ipykernel_9420\3447878239.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  y=pd.read_csv("result.txt",sep="/t",names=['Roll no','result'])

FileNotFoundError: [Errno 2] No such file or directory: 'result.txt'

In [12]:
f=open("C:/Users/admin/Downloads/Student.txt","r")

In [13]:
f